project_id    = "natural-region-452705-m6"
region        = "us-central1"
instance_name = "my-vm"
machine_type  = "n1-standard-1"
zone          = "us-central1-a"
image         = "debian-cloud/debian-11"
network       = "default"
